//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.18 at 05:50:01 PM CEST 
//


package xml.papersapp.model.cover_letters;

import xml.papersapp.model.cover_letter.CoverLetter;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.tim12.com/cover_letter}CoverLetter"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coverLetter"
})
@XmlRootElement(name = "CoverLetters")
public class CoverLetters {

    @XmlElement(name = "CoverLetter", namespace = "http://www.tim12.com/cover_letter")
    protected List<CoverLetter> coverLetter;

    /**
     * Gets the value of the coverLetter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coverLetter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoverLetter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoverLetter }
     * 
     * 
     */
    public List<CoverLetter> getCoverLetter() {
        if (coverLetter == null) {
            coverLetter = new ArrayList<CoverLetter>();
        }
        return this.coverLetter;
    }

}
