//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.19 at 12:19:06 PM CEST 
//


package xml.papersapp.model.notification;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for TNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TNotification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sciencePaperTitle">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value=".+(\s.+){0,15}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reviewerEmail">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TNotification", propOrder = {
    "sciencePaperTitle",
    "content",
    "reviewerEmail"
})
@XmlRootElement(name = "Notification")
public class TNotification {

    @XmlElement(required = true)
    protected String sciencePaperTitle;
    @XmlElement(required = true)
    protected String content;
    @XmlElement(required = true)
    protected String reviewerEmail;

    /**
     * Gets the value of the sciencePaperTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSciencePaperTitle() {
        return sciencePaperTitle;
    }

    /**
     * Sets the value of the sciencePaperTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSciencePaperTitle(String value) {
        this.sciencePaperTitle = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the reviewerEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewerEmail() {
        return reviewerEmail;
    }

    /**
     * Sets the value of the reviewerEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewerEmail(String value) {
        this.reviewerEmail = value;
    }

}
