//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.12 at 03:39:33 PM CEST 
//


package xml.papersapp.model.science_paper;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tim12.science_paper package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TParagraphTable_QNAME = new QName("http://www.tim12.com/science_paper", "table");
    private final static QName _TParagraphPicture_QNAME = new QName("http://www.tim12.com/science_paper", "picture");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tim12.science_paper
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TSection }
     * 
     */
    public TSection createTSection() {
        return new TSection();
    }

    /**
     * Create an instance of {@link TAbstract }
     * 
     */
    public TAbstract createTAbstract() {
        return new TAbstract();
    }

    /**
     * Create an instance of {@link SciencePaper }
     * 
     */
    public SciencePaper createSciencePaper() {
        return new SciencePaper();
    }

    /**
     * Create an instance of {@link TAuthors }
     * 
     */
    public TAuthors createTAuthors() {
        return new TAuthors();
    }

    /**
     * Create an instance of {@link TReviewers }
     * 
     */
    public TReviewers createTReviewers() {
        return new TReviewers();
    }

    /**
     * Create an instance of {@link TContent }
     * 
     */
    public TContent createTContent() {
        return new TContent();
    }

    /**
     * Create an instance of {@link TReferences }
     * 
     */
    public TReferences createTReferences() {
        return new TReferences();
    }

    /**
     * Create an instance of {@link TRow }
     * 
     */
    public TRow createTRow() {
        return new TRow();
    }

    /**
     * Create an instance of {@link TPicture }
     * 
     */
    public TPicture createTPicture() {
        return new TPicture();
    }

    /**
     * Create an instance of {@link TParagraph }
     * 
     */
    public TParagraph createTParagraph() {
        return new TParagraph();
    }

    /**
     * Create an instance of {@link TAuthor }
     * 
     */
    public TAuthor createTAuthor() {
        return new TAuthor();
    }

    /**
     * Create an instance of {@link TReference }
     * 
     */
    public TReference createTReference() {
        return new TReference();
    }

    /**
     * Create an instance of {@link TTable }
     * 
     */
    public TTable createTTable() {
        return new TTable();
    }

    /**
     * Create an instance of {@link TSection.Title }
     * 
     */
    public TSection.Title createTSectionTitle() {
        return new TSection.Title();
    }

    /**
     * Create an instance of {@link TAbstract.Keywords }
     * 
     */
    public TAbstract.Keywords createTAbstractKeywords() {
        return new TAbstract.Keywords();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TTable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tim12.com/science_paper", name = "table", scope = TParagraph.class)
    public JAXBElement<TTable> createTParagraphTable(TTable value) {
        return new JAXBElement<TTable>(_TParagraphTable_QNAME, TTable.class, TParagraph.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TPicture }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tim12.com/science_paper", name = "picture", scope = TParagraph.class)
    public JAXBElement<TPicture> createTParagraphPicture(TPicture value) {
        return new JAXBElement<TPicture>(_TParagraphPicture_QNAME, TPicture.class, TParagraph.class, value);
    }

}
