//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.12 at 03:41:55 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tim12.com/cover_letter", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xml.papersapp.model.cover_letter;
